import * as ElementPlusIcons from '@element-plus/icons-vue'

const iconMap = {
  Menu: 'Menu',
  Lock: 'Lock',
  Bell: 'Bell',
  User: 'User',
  Setting: 'Setting',
  SwitchButton: 'SwitchButton',
  DataAnalysis: 'DataAnalysis',
  Search: 'Search',
  Aim: 'Aim',
  Monitor: 'Monitor',
  Document: 'Document',
  ArrowRight: 'ArrowRight',
  Refresh: 'Refresh',
  Warning: 'Warning',
  CircleCheck: 'CircleCheck',
  CircleClose: 'CircleClose',
  Close: 'Close',
  View: 'View',
  Delete: 'Delete',
  Link: 'Link',
  RefreshLeft: 'RefreshLeft',
  Position: 'Position',
  Plus: 'Plus',
  Edit: 'Edit',
  Download: 'Download',
  Upload: 'Upload',
  Filter: 'Filter',
  Sort: 'Sort',
  More: 'More',
  Check: 'Check',
  Clock: 'Clock',
  Calendar: 'Calendar',
  Location: 'Location',
  Phone: 'Phone',
  Message: 'Message',
  Star: 'Star',
  Heart: 'Heart',
  Share: 'Share',
  Printer: 'Printer',
  ZoomIn: 'ZoomIn',
  ZoomOut: 'ZoomOut',
  FullScreen: 'FullScreen',
  Crop: 'Crop',
  Picture: 'Picture',
  Camera: 'Camera',
  VideoPlay: 'VideoPlay',
  VideoPause: 'VideoPause',
  Microphone: 'Microphone',
  Mute: 'Mute',
  Volume: 'Volume',
  Headset: 'Headset',
  Connection: 'Connection',
  Wifi: 'Wifi',
  Signal: 'Signal',
  SortDown: 'SortDown',
  SortUp: 'SortUp',
  SortCustom: 'SortCustom',
  SortAscending: 'SortAscending',
  SortDescending: 'SortDescending',
  MoreFilled: 'MoreFilled',
  ArrowUp: 'ArrowUp',
  ArrowDown: 'ArrowDown',
  ArrowLeft: 'ArrowLeft',
  DArrowLeft: 'DArrowLeft',
  DArrowRight: 'DArrowRight',
  DArrowUp: 'DArrowUp',
  DArrowDown: 'DArrowDown',
  CaretTop: 'CaretTop',
  CaretBottom: 'CaretBottom',
  CaretLeft: 'CaretLeft',
  CaretRight: 'CaretRight',
  CaretLeftFilled: 'CaretLeftFilled',
  CaretRightFilled: 'CaretRightFilled',
  CaretTopFilled: 'CaretTopFilled',
  CaretBottomFilled: 'CaretBottomFilled',
  Top: 'Top',
  Bottom: 'Bottom',
  Left: 'Left',
  Right: 'Right',
  Back: 'Back',
  RightArrow: 'RightArrow',
  TopLeft: 'TopLeft',
  TopRight: 'TopRight',
  BottomLeft: 'BottomLeft',
  BottomRight: 'BottomRight',
  TopLeftArrow: 'TopLeftArrow',
  TopRightArrow: 'TopRightArrow',
  BottomLeftArrow: 'BottomLeftArrow',
  BottomRightArrow: 'BottomRightArrow',
  CirclePlus: 'CirclePlus',
  CirclePlusFilled: 'CirclePlusFilled',
  Remove: 'Remove',
  RemoveFilled: 'RemoveFilled',
  SemiSelect: 'SemiSelect',
  Select: 'Select',
  CircleCheckFilled: 'CircleCheckFilled',
  SuccessFilled: 'SuccessFilled',
  WarningFilled: 'WarningFilled',
  CircleCloseFilled: 'CircleCloseFilled',
  InfoFilled: 'InfoFilled',
  QuestionFilled: 'QuestionFilled',
  CirclePlus: 'CirclePlus',
  Remove: 'Remove',
  SemiSelect: 'SemiSelect',
  Select: 'Select',
  CircleCheckFilled: 'CircleCheckFilled',
  SuccessFilled: 'SuccessFilled',
  WarningFilled: 'WarningFilled',
  CircleCloseFilled: 'CircleCloseFilled',
  InfoFilled: 'InfoFilled',
  QuestionFilled: 'QuestionFilled',
  Loading: 'Loading',
  LoadingFilled: 'LoadingFilled',
  View: 'View',
  Hide: 'Hide',
  Unlock: 'Unlock',
  Lock: 'Lock',
  Aim: 'Aim',
  Crop: 'Crop',
  Edit: 'Edit',
  Delete: 'Delete',
  Download: 'Download',
  Upload: 'Upload',
  ZoomIn: 'ZoomIn',
  ZoomOut: 'ZoomOut',
  Share: 'Share',
  Star: 'Star',
  StarFilled: 'StarFilled',
  Like: 'Like',
  LikeFilled: 'LikeFilled',
  Dislike: 'Dislike',
  DislikeFilled: 'DislikeFilled',
  ChatDotRound: 'ChatDotRound',
  ChatDotSquare: 'ChatDotSquare',
  ChatLineRound: 'ChatLineRound',
  ChatLineSquare: 'ChatLineSquare',
  Message: 'Message',
  MessageBox: 'MessageBox',
  MessageFilled: 'MessageFilled',
  Notification: 'Notification',
  BellFilled: 'BellFilled',
  Service: 'Service',
  Position: 'Position',
  Connection: 'Connection',
  Phone: 'Phone',
  PhoneFilled: 'PhoneFilled',
  Microphone: 'Microphone',
  MicrophoneFilled: 'MicrophoneFilled',
  Mute: 'Mute',
  MuteNotification: 'MuteNotification',
  Headset: 'Headset',
  HeadsetFilled: 'HeadsetFilled',
  VideoCamera: 'VideoCamera',
  VideoCameraFilled: 'VideoCameraFilled',
  VideoPlay: 'VideoPlay',
  VideoPause: 'VideoPause',
  VideoPlayFilled: 'VideoPlayFilled',
  VideoPauseFilled: 'VideoPauseFilled',
  Monitor: 'Monitor',
  TurnOff: 'TurnOff',
  RefreshRight: 'RefreshRight',
  RefreshLeft: 'RefreshLeft',
  Refresh: 'Refresh',
  RefreshFilled: 'RefreshFilled',
  Sort: 'Sort',
  SortDown: 'SortDown',
  SortUp: 'SortUp',
  SortDescending: 'SortDescending',
  SortAscending: 'SortAscending',
  SortCustom: 'SortCustom',
  Filter: 'Filter',
  FilterFilled: 'FilterFilled',
  More: 'More',
  MoreFilled: 'MoreFilled',
  Menu: 'Menu',
  Grid: 'Grid',
  GridFilled: 'GridFilled',
  List: 'List',
  Operation: 'Operation',
  DataAnalysis: 'DataAnalysis',
  DataLine: 'DataLine',
  DataBoard: 'DataBoard',
  PieChart: 'PieChart',
  Histogram: 'Histogram',
  LineChart: 'LineChart',
  TrendCharts: 'TrendCharts',
  ScaleToOriginal: 'ScaleToOriginal',
  Date: 'Date',
  Calendar: 'Calendar',
  Clock: 'Clock',
  Timer: 'Timer',
  AlarmClock: 'AlarmClock',
  Stopwatch: 'Stopwatch',
  Notebook: 'Notebook',
  Tickets: 'Tickets',
  Management: 'Management',
  Memo: 'Memo',
  EditPen: 'EditPen',
  Edit: 'Edit',
  Document: 'Document',
  DocumentCopy: 'DocumentCopy',
  DocumentDelete: 'DocumentDelete',
  DocumentAdd: 'DocumentAdd',
  DocumentChecked: 'DocumentChecked',
  DocumentRemove: 'DocumentRemove',
  Folder: 'Folder',
  FolderOpened: 'FolderOpened',
  FolderAdd: 'FolderAdd',
  FolderDelete: 'FolderDelete',
  FolderChecked: 'FolderChecked',
  FolderRemove: 'FolderRemove',
  Download: 'Download',
  Upload: 'Upload',
  Picture: 'Picture',
  PictureFilled: 'PictureFilled',
  PictureRounded: 'PictureRounded',
  Camera: 'Camera',
  CameraFilled: 'CameraFilled',
  VideoCamera: 'VideoCamera',
  VideoCameraFilled: 'VideoCameraFilled',
  Files: 'Files',
  Link: 'Link',
  Paperclip: 'Paperclip',
  Printer: 'Printer',
  Reading: 'Reading',
  ReadingLamp: 'ReadingLamp',
  Collection: 'Collection',
  CollectionTag: 'CollectionTag',
  Files: 'Files',
  Notebook: 'Notebook',
  NoteBook: 'NoteBook',
  PriceTag: 'PriceTag',
  PriceTagFilled: 'PriceTagFilled',
  Discount: 'Discount',
  Wallet: 'Wallet',
  WalletFilled: 'WalletFilled',
  Coin: 'Coin',
  Money: 'Money',
  CreditCard: 'CreditCard',
  Wallet: 'Wallet',
  WalletFilled: 'WalletFilled',
  Goods: 'Goods',
  SoldOut: 'SoldOut',
  ShoppingBag: 'ShoppingBag',
  ShoppingBagFilled: 'ShoppingBagFilled',
  ShoppingCart: 'ShoppingCart',
  ShoppingCartFilled: 'ShoppingCartFilled',
  ShoppingCartFull: 'ShoppingCartFull',
  Box: 'Box',
  BoxFilled: 'BoxFilled',
  Briefcase: 'Briefcase',
  Suitcase: 'Suitcase',
  SuitcaseLine: 'SuitcaseLine',
  SuitcaseFilled: 'SuitcaseFilled',
  Receiving: 'Receiving',
  Sell: 'Sell',
  SoldOut: 'SoldOut',
  Discount: 'Discount',
  Ticket: 'Ticket',
  Tickets: 'Tickets',
  FirstAidKit: 'FirstAidKit',
  Trophy: 'Trophy',
  TrophyBase: 'TrophyBase',
  Medal: 'Medal',
  MedalFilled: 'MedalFilled',
  Stamp: 'Stamp',
  StampFilled: 'StampFilled',
  Present: 'Present',
  PresentFilled: 'PresentFilled',
  Promotion: 'Promotion',
  PromotionDiscount: 'PromotionDiscount',
  PromotionActivity: 'PromotionActivity',
  Present: 'Present',
  PresentFilled: 'PresentFilled',
  PresentCard: 'PresentCard',
  PresentCardFilled: 'PresentCardFilled',
  PresentOne: 'PresentOne',
  PresentTwo: 'PresentTwo',
  PresentThree: 'PresentThree',
  PresentFour: 'PresentFour',
  PresentFive: 'PresentFive',
  PresentSix: 'PresentSix',
  PresentSeven: 'PresentSeven',
  PresentEight: 'PresentEight',
  PresentNine: 'PresentNine',
  PresentTen: 'PresentTen',
  PresentEleven: 'PresentEleven',
  PresentTwelve: 'PresentTwelve',
  PresentThirteen: 'PresentThirteen',
  PresentFourteen: 'PresentFourteen',
  PresentFifteen: 'PresentFifteen',
  PresentSixteen: 'PresentSixteen',
  PresentSeventeen: 'PresentSeventeen',
  PresentEighteen: 'PresentEighteen',
  PresentNineteen: 'PresentNineteen',
  PresentTwenty: 'PresentTwenty',
  PresentTwentyOne: 'PresentTwentyOne',
  PresentTwentyTwo: 'PresentTwentyTwo',
  PresentTwentyThree: 'PresentTwentyThree',
  PresentTwentyFour: 'PresentTwentyFour',
  PresentTwentyFive: 'PresentTwentyFive',
  PresentTwentySix: 'PresentTwentySix',
  PresentTwentySeven: 'PresentTwentySeven',
  PresentTwentyEight: 'PresentTwentyEight',
  PresentTwentyNine: 'PresentTwentyNine',
  PresentThirty: 'PresentThirty',
  PresentThirtyOne: 'PresentThirtyOne',
  PresentThirtyTwo: 'PresentThirtyTwo',
  PresentThirtyThree: 'PresentThirtyThree',
  PresentThirtyFour: 'PresentThirtyFour',
  PresentThirtyFive: 'PresentThirtyFive',
  PresentThirtySix: 'PresentThirtySix',
  PresentThirtySeven: 'PresentThirtySeven',
  PresentThirtyEight: 'PresentThirtyEight',
  PresentThirtyNine: 'PresentThirtyNine',
  PresentForty: 'PresentForty',
  PresentFortyOne: 'PresentFortyOne',
  PresentFortyTwo: 'PresentFortyTwo',
  PresentFortyThree: 'PresentFortyThree',
  PresentFortyFour: 'PresentFortyFour',
  PresentFortyFive: 'PresentFortyFive',
  PresentFortySix: 'PresentFortySix',
  PresentFortySeven: 'PresentFortySeven',
  PresentFortyEight: 'PresentFortyEight',
  PresentFortyNine: 'PresentFortyNine',
  PresentFifty: 'PresentFifty',
  PresentFiftyOne: 'PresentFiftyOne',
  PresentFiftyTwo: 'PresentFiftyTwo',
  PresentFiftyThree: 'PresentFiftyThree',
  PresentFiftyFour: 'PresentFiftyFour',
  PresentFiftyFive: 'PresentFiftyFive',
  PresentFiftySix: 'PresentFiftySix',
  PresentFiftySeven: 'PresentFiftySeven',
  PresentFiftyEight: 'PresentFiftyEight',
  PresentFiftyNine: 'PresentFiftyNine',
  PresentSixty: 'PresentSixty',
  PresentSixtyOne: 'PresentSixtyOne',
  PresentSixtyTwo: 'PresentSixtyTwo',
  PresentSixtyThree: 'PresentSixtyThree',
  PresentSixtyFour: 'PresentSixtyFour',
  PresentSixtyFive: 'PresentSixtyFive',
  PresentSixtySix: 'PresentSixtySix',
  PresentSixtySeven: 'PresentSixtySeven',
  PresentSixtyEight: 'PresentSixtyEight',
  PresentSixtyNine: 'PresentSixtyNine',
  PresentSeventy: 'PresentSeventy',
  PresentSeventyOne: 'PresentSeventyOne',
  PresentSeventyTwo: 'PresentSeventyTwo',
  PresentSeventyThree: 'PresentSeventyThree',
  PresentSeventyFour: 'PresentSeventyFour',
  PresentSeventyFive: 'PresentSeventyFive',
  PresentSeventySix: 'PresentSeventySix',
  PresentSeventySeven: 'PresentSeventySeven',
  PresentSeventyEight: 'PresentSeventyEight',
  PresentSeventyNine: 'PresentSeventyNine',
  PresentEighty: 'PresentEighty',
  PresentEightyOne: 'PresentEightyOne',
  PresentEightyTwo: 'PresentEightyTwo',
  PresentEightyThree: 'PresentEightyThree',
  PresentEightyFour: 'PresentEightyFour',
  PresentEightyFive: 'PresentEightyFive',
  PresentEightySix: 'PresentEightySix',
  PresentEightySeven: 'PresentEightySeven',
  PresentEightyEight: 'PresentEightyEight',
  PresentEightyNine: 'PresentEightyNine',
  PresentNinety: 'PresentNinety',
  PresentNinetyOne: 'PresentNinetyOne',
  PresentNinetyTwo: 'PresentNinetyTwo',
  PresentNinetyThree: 'PresentNinetyThree',
  PresentNinetyFour: 'PresentNinetyFour',
  PresentNinetyFive: 'PresentNinetyFive',
  PresentNinetySix: 'PresentNinetySix',
  PresentNinetySeven: 'PresentNinetySeven',
  PresentNinetyEight: 'PresentNinetyEight',
  PresentNinetyNine: 'PresentNinetyNine',
  PresentOneHundred: 'PresentOneHundred'
}

const iconCache = new Map()

export function getIcon(name) {
  if (iconCache.has(name)) {
    return iconCache.get(name)
  }

  const iconName = iconMap[name]
  if (!iconName) {
    console.warn(`Icon "${name}" not found in icon map`)
    return null
  }

  const iconComponent = ElementPlusIcons[iconName]
  if (!iconComponent) {
    console.warn(`Icon component "${iconName}" not found in Element Plus icons`)
    return null
  }

  iconCache.set(name, iconComponent)
  return iconComponent
}

export function getAllIcons() {
  return Object.keys(iconMap)
}

export function getIconMap() {
  return { ...iconMap }
}

export function registerIcon(name, component) {
  iconMap[name] = name
  iconCache.set(name, component)
}

export function clearIconCache() {
  iconCache.clear()
}

export default {
  getIcon,
  getAllIcons,
  getIconMap,
  registerIcon,
  clearIconCache
}
